class JwtAuthError(Exception): ...


class AccessKeyAuthError(Exception): ...


class LLMNotExistError(Exception): ...


class LangNotSupportError(Exception): ...


class InputParamsError(Exception): ...